// Code generated by protoc-gen-go. DO NOT EDIT.
// source: networkinterface.proto

package network

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/microsoft/moc/rpc/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetworkInterface_NetworkInterfaceType int32

const (
	NetworkInterface_Local  NetworkInterface_NetworkInterfaceType = 0
	NetworkInterface_Remote NetworkInterface_NetworkInterfaceType = 1
)

var NetworkInterface_NetworkInterfaceType_name = map[int32]string{
	0: "Local",
	1: "Remote",
}

var NetworkInterface_NetworkInterfaceType_value = map[string]int32{
	"Local":  0,
	"Remote": 1,
}

func (x NetworkInterface_NetworkInterfaceType) String() string {
	return proto.EnumName(NetworkInterface_NetworkInterfaceType_name, int32(x))
}

func (NetworkInterface_NetworkInterfaceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_72a481e6e4e12e01, []int{3, 0}
}

type NetworkInterfaceRequest struct {
	NetworkInterfaces    []*NetworkInterface `protobuf:"bytes,1,rep,name=NetworkInterfaces,proto3" json:"NetworkInterfaces,omitempty"`
	OperationType        common.Operation    `protobuf:"varint,2,opt,name=OperationType,proto3,enum=moc.Operation" json:"OperationType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NetworkInterfaceRequest) Reset()         { *m = NetworkInterfaceRequest{} }
func (m *NetworkInterfaceRequest) String() string { return proto.CompactTextString(m) }
func (*NetworkInterfaceRequest) ProtoMessage()    {}
func (*NetworkInterfaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a481e6e4e12e01, []int{0}
}

func (m *NetworkInterfaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInterfaceRequest.Unmarshal(m, b)
}
func (m *NetworkInterfaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInterfaceRequest.Marshal(b, m, deterministic)
}
func (m *NetworkInterfaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInterfaceRequest.Merge(m, src)
}
func (m *NetworkInterfaceRequest) XXX_Size() int {
	return xxx_messageInfo_NetworkInterfaceRequest.Size(m)
}
func (m *NetworkInterfaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInterfaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInterfaceRequest proto.InternalMessageInfo

func (m *NetworkInterfaceRequest) GetNetworkInterfaces() []*NetworkInterface {
	if m != nil {
		return m.NetworkInterfaces
	}
	return nil
}

func (m *NetworkInterfaceRequest) GetOperationType() common.Operation {
	if m != nil {
		return m.OperationType
	}
	return common.Operation_GET
}

type NetworkInterfaceResponse struct {
	NetworkInterfaces    []*NetworkInterface `protobuf:"bytes,1,rep,name=NetworkInterfaces,proto3" json:"NetworkInterfaces,omitempty"`
	Result               *wrappers.BoolValue `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error                string              `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NetworkInterfaceResponse) Reset()         { *m = NetworkInterfaceResponse{} }
func (m *NetworkInterfaceResponse) String() string { return proto.CompactTextString(m) }
func (*NetworkInterfaceResponse) ProtoMessage()    {}
func (*NetworkInterfaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a481e6e4e12e01, []int{1}
}

func (m *NetworkInterfaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInterfaceResponse.Unmarshal(m, b)
}
func (m *NetworkInterfaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInterfaceResponse.Marshal(b, m, deterministic)
}
func (m *NetworkInterfaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInterfaceResponse.Merge(m, src)
}
func (m *NetworkInterfaceResponse) XXX_Size() int {
	return xxx_messageInfo_NetworkInterfaceResponse.Size(m)
}
func (m *NetworkInterfaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInterfaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInterfaceResponse proto.InternalMessageInfo

func (m *NetworkInterfaceResponse) GetNetworkInterfaces() []*NetworkInterface {
	if m != nil {
		return m.NetworkInterfaces
	}
	return nil
}

func (m *NetworkInterfaceResponse) GetResult() *wrappers.BoolValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *NetworkInterfaceResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type IpConfiguration struct {
	Ipaddress               string                    `protobuf:"bytes,1,opt,name=ipaddress,proto3" json:"ipaddress,omitempty"`
	Prefixlength            string                    `protobuf:"bytes,2,opt,name=prefixlength,proto3" json:"prefixlength,omitempty"`
	Subnetid                string                    `protobuf:"bytes,3,opt,name=subnetid,proto3" json:"subnetid,omitempty"`
	Primary                 bool                      `protobuf:"varint,4,opt,name=primary,proto3" json:"primary,omitempty"`
	Loadbalanceraddresspool []string                  `protobuf:"bytes,5,rep,name=loadbalanceraddresspool,proto3" json:"loadbalanceraddresspool,omitempty"`
	Allocation              common.IPAllocationMethod `protobuf:"varint,6,opt,name=allocation,proto3,enum=moc.IPAllocationMethod" json:"allocation,omitempty"`
	Gateway                 string                    `protobuf:"bytes,7,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Virtualnetworkname      string                    `protobuf:"bytes,8,opt,name=virtualnetworkname,proto3" json:"virtualnetworkname,omitempty"`
	Subnetname              string                    `protobuf:"bytes,9,opt,name=subnetname,proto3" json:"subnetname,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                  `json:"-"`
	XXX_unrecognized        []byte                    `json:"-"`
	XXX_sizecache           int32                     `json:"-"`
}

func (m *IpConfiguration) Reset()         { *m = IpConfiguration{} }
func (m *IpConfiguration) String() string { return proto.CompactTextString(m) }
func (*IpConfiguration) ProtoMessage()    {}
func (*IpConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a481e6e4e12e01, []int{2}
}

func (m *IpConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpConfiguration.Unmarshal(m, b)
}
func (m *IpConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpConfiguration.Marshal(b, m, deterministic)
}
func (m *IpConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpConfiguration.Merge(m, src)
}
func (m *IpConfiguration) XXX_Size() int {
	return xxx_messageInfo_IpConfiguration.Size(m)
}
func (m *IpConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_IpConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_IpConfiguration proto.InternalMessageInfo

func (m *IpConfiguration) GetIpaddress() string {
	if m != nil {
		return m.Ipaddress
	}
	return ""
}

func (m *IpConfiguration) GetPrefixlength() string {
	if m != nil {
		return m.Prefixlength
	}
	return ""
}

func (m *IpConfiguration) GetSubnetid() string {
	if m != nil {
		return m.Subnetid
	}
	return ""
}

func (m *IpConfiguration) GetPrimary() bool {
	if m != nil {
		return m.Primary
	}
	return false
}

func (m *IpConfiguration) GetLoadbalanceraddresspool() []string {
	if m != nil {
		return m.Loadbalanceraddresspool
	}
	return nil
}

func (m *IpConfiguration) GetAllocation() common.IPAllocationMethod {
	if m != nil {
		return m.Allocation
	}
	return common.IPAllocationMethod_Invalid
}

func (m *IpConfiguration) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *IpConfiguration) GetVirtualnetworkname() string {
	if m != nil {
		return m.Virtualnetworkname
	}
	return ""
}

func (m *IpConfiguration) GetSubnetname() string {
	if m != nil {
		return m.Subnetname
	}
	return ""
}

type NetworkInterface struct {
	Name                 string                                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string                                `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 NetworkInterface_NetworkInterfaceType `protobuf:"varint,3,opt,name=type,proto3,enum=moc.cloudagent.network.NetworkInterface_NetworkInterfaceType" json:"type,omitempty"`
	IpConfigurations     []*IpConfiguration                    `protobuf:"bytes,4,rep,name=ipConfigurations,proto3" json:"ipConfigurations,omitempty"`
	Macaddress           string                                `protobuf:"bytes,5,opt,name=macaddress,proto3" json:"macaddress,omitempty"`
	Dns                  *common.Dns                           `protobuf:"bytes,6,opt,name=dns,proto3" json:"dns,omitempty"`
	NodeName             string                                `protobuf:"bytes,7,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	GroupName            string                                `protobuf:"bytes,8,opt,name=groupName,proto3" json:"groupName,omitempty"`
	LocationName         string                                `protobuf:"bytes,9,opt,name=locationName,proto3" json:"locationName,omitempty"`
	Status               *common.Status                        `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	VirtualMachineName   string                                `protobuf:"bytes,11,opt,name=virtualMachineName,proto3" json:"virtualMachineName,omitempty"`
	IovWeight            uint32                                `protobuf:"varint,12,opt,name=iovWeight,proto3" json:"iovWeight,omitempty"`
	Tags                 *common.Tags                          `protobuf:"bytes,13,opt,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *NetworkInterface) Reset()         { *m = NetworkInterface{} }
func (m *NetworkInterface) String() string { return proto.CompactTextString(m) }
func (*NetworkInterface) ProtoMessage()    {}
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_72a481e6e4e12e01, []int{3}
}

func (m *NetworkInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInterface.Unmarshal(m, b)
}
func (m *NetworkInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInterface.Marshal(b, m, deterministic)
}
func (m *NetworkInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInterface.Merge(m, src)
}
func (m *NetworkInterface) XXX_Size() int {
	return xxx_messageInfo_NetworkInterface.Size(m)
}
func (m *NetworkInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInterface.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInterface proto.InternalMessageInfo

func (m *NetworkInterface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkInterface) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NetworkInterface) GetType() NetworkInterface_NetworkInterfaceType {
	if m != nil {
		return m.Type
	}
	return NetworkInterface_Local
}

func (m *NetworkInterface) GetIpConfigurations() []*IpConfiguration {
	if m != nil {
		return m.IpConfigurations
	}
	return nil
}

func (m *NetworkInterface) GetMacaddress() string {
	if m != nil {
		return m.Macaddress
	}
	return ""
}

func (m *NetworkInterface) GetDns() *common.Dns {
	if m != nil {
		return m.Dns
	}
	return nil
}

func (m *NetworkInterface) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *NetworkInterface) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *NetworkInterface) GetLocationName() string {
	if m != nil {
		return m.LocationName
	}
	return ""
}

func (m *NetworkInterface) GetStatus() *common.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *NetworkInterface) GetVirtualMachineName() string {
	if m != nil {
		return m.VirtualMachineName
	}
	return ""
}

func (m *NetworkInterface) GetIovWeight() uint32 {
	if m != nil {
		return m.IovWeight
	}
	return 0
}

func (m *NetworkInterface) GetTags() *common.Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterEnum("moc.cloudagent.network.NetworkInterface_NetworkInterfaceType", NetworkInterface_NetworkInterfaceType_name, NetworkInterface_NetworkInterfaceType_value)
	proto.RegisterType((*NetworkInterfaceRequest)(nil), "moc.cloudagent.network.NetworkInterfaceRequest")
	proto.RegisterType((*NetworkInterfaceResponse)(nil), "moc.cloudagent.network.NetworkInterfaceResponse")
	proto.RegisterType((*IpConfiguration)(nil), "moc.cloudagent.network.IpConfiguration")
	proto.RegisterType((*NetworkInterface)(nil), "moc.cloudagent.network.NetworkInterface")
}

func init() { proto.RegisterFile("networkinterface.proto", fileDescriptor_72a481e6e4e12e01) }

var fileDescriptor_72a481e6e4e12e01 = []byte{
	// 708 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x6e, 0xdb, 0x38,
	0x10, 0x8e, 0xfc, 0x17, 0x7b, 0x9c, 0x64, 0xbd, 0xdc, 0x6c, 0x22, 0x18, 0xbb, 0x81, 0xe1, 0x3d,
	0xac, 0x2f, 0x2b, 0xed, 0x7a, 0x0b, 0xb4, 0x97, 0x1e, 0x92, 0xb6, 0x07, 0x03, 0x8d, 0xdb, 0x32,
	0x41, 0x0a, 0xf4, 0x46, 0x4b, 0xb4, 0x4c, 0x44, 0xe2, 0xa8, 0x24, 0x95, 0x34, 0x2f, 0xd0, 0x57,
	0xe9, 0x33, 0x14, 0xe8, 0xf3, 0xf4, 0x39, 0x0a, 0x51, 0xf2, 0x7f, 0x02, 0xe4, 0xd2, 0x9b, 0xe6,
	0x9b, 0x8f, 0x33, 0xc3, 0xef, 0x1b, 0x11, 0x8e, 0x24, 0x37, 0xb7, 0xa8, 0xae, 0x85, 0x34, 0x5c,
	0x4d, 0x59, 0xc0, 0xbd, 0x54, 0xa1, 0x41, 0x72, 0x94, 0x60, 0xe0, 0x05, 0x31, 0x66, 0x21, 0x8b,
	0xb8, 0x34, 0x5e, 0x49, 0xeb, 0x9e, 0x44, 0x88, 0x51, 0xcc, 0x7d, 0xcb, 0x9a, 0x64, 0x53, 0xff,
	0x56, 0xb1, 0x34, 0xe5, 0x4a, 0x17, 0xe7, 0xba, 0x7b, 0x01, 0x26, 0x09, 0xca, 0x32, 0xfa, 0xad,
	0x3c, 0xb6, 0x0a, 0xf6, 0xbf, 0x38, 0x70, 0x3c, 0x2e, 0xf0, 0xd1, 0xbc, 0x2b, 0xe5, 0x1f, 0x33,
	0xae, 0x0d, 0xb9, 0x82, 0x5f, 0x37, 0x53, 0xda, 0x75, 0x7a, 0xd5, 0x41, 0x7b, 0x38, 0xf0, 0xee,
	0x1f, 0xc9, 0xdb, 0xaa, 0xb5, 0x5d, 0x82, 0x3c, 0x81, 0xfd, 0x37, 0x29, 0x57, 0xcc, 0x08, 0x94,
	0x97, 0x77, 0x29, 0x77, 0x2b, 0x3d, 0x67, 0x70, 0x30, 0x3c, 0xb0, 0x35, 0x17, 0x19, 0xba, 0x4e,
	0xea, 0x7f, 0x73, 0xc0, 0xdd, 0x9e, 0x54, 0xa7, 0x28, 0x35, 0xff, 0x69, 0xa3, 0x0e, 0xa1, 0x41,
	0xb9, 0xce, 0x62, 0x63, 0x67, 0x6c, 0x0f, 0xbb, 0x5e, 0x21, 0xb9, 0x37, 0x97, 0xdc, 0x3b, 0x43,
	0x8c, 0xaf, 0x58, 0x9c, 0x71, 0x5a, 0x32, 0xc9, 0x21, 0xd4, 0x5f, 0x29, 0x85, 0xca, 0xad, 0xf6,
	0x9c, 0x41, 0x8b, 0x16, 0x41, 0xff, 0x7b, 0x05, 0x7e, 0x19, 0xa5, 0x2f, 0x50, 0x4e, 0x45, 0x94,
	0x15, 0xd7, 0x22, 0x7f, 0x40, 0x4b, 0xa4, 0x2c, 0x0c, 0x15, 0xd7, 0xf9, 0xb4, 0x39, 0x7b, 0x09,
	0x90, 0x3e, 0xec, 0xa5, 0x8a, 0x4f, 0xc5, 0xa7, 0x98, 0xcb, 0xc8, 0xcc, 0xec, 0x04, 0x2d, 0xba,
	0x86, 0x91, 0x2e, 0x34, 0x75, 0x36, 0x91, 0xdc, 0x88, 0xb0, 0x6c, 0xb7, 0x88, 0x89, 0x0b, 0xbb,
	0xa9, 0x12, 0x09, 0x53, 0x77, 0x6e, 0xad, 0xe7, 0x0c, 0x9a, 0x74, 0x1e, 0x92, 0x67, 0x70, 0x1c,
	0x23, 0x0b, 0x27, 0x2c, 0x66, 0x32, 0xe0, 0xaa, 0x6c, 0x98, 0x22, 0xc6, 0x6e, 0xbd, 0x57, 0x1d,
	0xb4, 0xe8, 0x43, 0x69, 0xf2, 0x14, 0x80, 0xc5, 0x31, 0x06, 0x76, 0x7e, 0xb7, 0x61, 0x7d, 0x3b,
	0xb6, 0x02, 0x8f, 0xde, 0x9e, 0x2e, 0x12, 0xe7, 0xdc, 0xcc, 0x30, 0xa4, 0x2b, 0xd4, 0x7c, 0x98,
	0x88, 0x19, 0x7e, 0xcb, 0xee, 0xdc, 0x5d, 0x3b, 0xe7, 0x3c, 0x24, 0x1e, 0x90, 0x1b, 0xa1, 0x4c,
	0xc6, 0xe2, 0xd2, 0x18, 0xc9, 0x12, 0xee, 0x36, 0x2d, 0xe9, 0x9e, 0x0c, 0x39, 0x01, 0x28, 0xae,
	0x68, 0x79, 0x2d, 0xcb, 0x5b, 0x41, 0xfa, 0x5f, 0x6b, 0xd0, 0xd9, 0x34, 0x92, 0x10, 0xa8, 0x59,
	0x7a, 0x21, 0xb2, 0xfd, 0x26, 0x07, 0x50, 0x11, 0x61, 0xa9, 0x6a, 0x45, 0x84, 0xe4, 0x1d, 0xd4,
	0x4c, 0xbe, 0x8d, 0x55, 0x7b, 0xab, 0xe7, 0x8f, 0x5d, 0x9b, 0x2d, 0x20, 0xdf, 0x56, 0x6a, 0x4b,
	0x91, 0x0b, 0xe8, 0x88, 0x75, 0xcf, 0xb5, 0x5b, 0xb3, 0x5b, 0xf9, 0xf7, 0x43, 0xe5, 0x37, 0x76,
	0x84, 0x6e, 0x15, 0xc8, 0x05, 0x48, 0x58, 0x30, 0x5f, 0x9b, 0x7a, 0x21, 0xc0, 0x12, 0x21, 0x5d,
	0xa8, 0x86, 0x52, 0x5b, 0x73, 0xda, 0xc3, 0xa6, 0xed, 0xf3, 0x52, 0x6a, 0x9a, 0x83, 0xf9, 0xbe,
	0x48, 0x0c, 0xf9, 0x38, 0xd7, 0xa2, 0xf0, 0x61, 0x11, 0xe7, 0xdb, 0x18, 0x29, 0xcc, 0xd2, 0xf1,
	0x52, 0xff, 0x25, 0x90, 0x6f, 0xe3, 0xdc, 0xcc, 0xf1, 0x52, 0xf8, 0x35, 0x8c, 0xfc, 0x05, 0x0d,
	0x6d, 0x98, 0xc9, 0xb4, 0x0b, 0xb6, 0x79, 0xdb, 0x36, 0xbf, 0xb0, 0x10, 0x2d, 0x53, 0x2b, 0x7e,
	0x9f, 0xb3, 0x60, 0x26, 0x64, 0x31, 0x4c, 0x7b, 0xcd, 0xef, 0x95, 0x8c, 0xfd, 0x49, 0xf0, 0xe6,
	0x3d, 0x17, 0xd1, 0xcc, 0xb8, 0x7b, 0x3d, 0x67, 0xb0, 0x4f, 0x97, 0x00, 0xf9, 0x13, 0x6a, 0x86,
	0x45, 0xda, 0xdd, 0xb7, 0x0d, 0x5b, 0xb6, 0xe1, 0x25, 0x8b, 0x34, 0xb5, 0x70, 0xff, 0x1f, 0x38,
	0xbc, 0xcf, 0x1e, 0xd2, 0x82, 0xfa, 0x6b, 0x0c, 0x58, 0xdc, 0xd9, 0x21, 0x90, 0xff, 0xe2, 0x09,
	0x1a, 0xde, 0x71, 0x86, 0x9f, 0x1d, 0xf8, 0x7d, 0x93, 0x7f, 0x9a, 0xdb, 0x43, 0x12, 0x68, 0x8c,
	0xe4, 0x0d, 0x5e, 0x73, 0xe2, 0x3f, 0xfa, 0x3d, 0x29, 0x9e, 0xd1, 0xee, 0xbf, 0x8f, 0x3f, 0x50,
	0xbc, 0x66, 0xfd, 0x9d, 0xb3, 0xff, 0x3e, 0xf8, 0x91, 0x30, 0xb3, 0x6c, 0xe2, 0x05, 0x98, 0xf8,
	0x89, 0x08, 0x14, 0x6a, 0x9c, 0x1a, 0x3f, 0xc1, 0xc0, 0x57, 0x69, 0xe0, 0x2f, 0xab, 0xf9, 0x65,
	0xb5, 0x49, 0xc3, 0x3e, 0x49, 0xff, 0xff, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xcb, 0x5d, 0x32,
	0x45, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NetworkInterfaceAgentClient is the client API for NetworkInterfaceAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetworkInterfaceAgentClient interface {
	Invoke(ctx context.Context, in *NetworkInterfaceRequest, opts ...grpc.CallOption) (*NetworkInterfaceResponse, error)
}

type networkInterfaceAgentClient struct {
	cc *grpc.ClientConn
}

func NewNetworkInterfaceAgentClient(cc *grpc.ClientConn) NetworkInterfaceAgentClient {
	return &networkInterfaceAgentClient{cc}
}

func (c *networkInterfaceAgentClient) Invoke(ctx context.Context, in *NetworkInterfaceRequest, opts ...grpc.CallOption) (*NetworkInterfaceResponse, error) {
	out := new(NetworkInterfaceResponse)
	err := c.cc.Invoke(ctx, "/moc.cloudagent.network.NetworkInterfaceAgent/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkInterfaceAgentServer is the server API for NetworkInterfaceAgent service.
type NetworkInterfaceAgentServer interface {
	Invoke(context.Context, *NetworkInterfaceRequest) (*NetworkInterfaceResponse, error)
}

// UnimplementedNetworkInterfaceAgentServer can be embedded to have forward compatible implementations.
type UnimplementedNetworkInterfaceAgentServer struct {
}

func (*UnimplementedNetworkInterfaceAgentServer) Invoke(ctx context.Context, req *NetworkInterfaceRequest) (*NetworkInterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}

func RegisterNetworkInterfaceAgentServer(s *grpc.Server, srv NetworkInterfaceAgentServer) {
	s.RegisterService(&_NetworkInterfaceAgent_serviceDesc, srv)
}

func _NetworkInterfaceAgent_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkInterfaceAgentServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moc.cloudagent.network.NetworkInterfaceAgent/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkInterfaceAgentServer).Invoke(ctx, req.(*NetworkInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkInterfaceAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moc.cloudagent.network.NetworkInterfaceAgent",
	HandlerType: (*NetworkInterfaceAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _NetworkInterfaceAgent_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "networkinterface.proto",
}
